apiVersion: v1
kind: Service
# Name of service
metadata:
  name: ping
spec:
  type: LoadBalancer
  # Which pod  qualify for forwarding the request
  selector:
    app: ping
  ports:
  - port: 80
    targetPort: 9696
