version: "3.9"
services:
  clothing-model:
    image: clothing-model-v4:v001
  gateway:
    image: zoomcamp-10-gateway:002
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - "9696:9696"